name: validate
on:
  - push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: 🧪 Run test script
        run: npm run test:coverage

      - name: 🏗 Run build script
        run: npm run build

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@v1
